export { default as Login } from "./login/Login";
export { default as Acceuil } from "./acceuil/Acceuil";
export { default as Signup } from "./signup/Signup";
export { default as Rdv } from "./rdv/Rdv";
export { default as Home } from "./home/Home";
export { default as Question } from "./question/Question";
export { default as Historique } from "./historique/Historique";
export { default as SecureRoute } from "./login/Login";
export { default as Contact } from "./contact/contact";
